name: Build obsidian plugin
# from argenos/nldates-obsidian

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*.*' # Push events to matching any tag format,  i.e. 1.0, 20.15.10

env:
  PLUGIN_NAME: obsidian-export-to-tex

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x' # You might need to adjust this value to your own version
      - name: Build
        id: build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build
          mv dist $
          zip -r $.zip $
          ls
          echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: $
          VERSION: $
        with:
          tag_name: $
          release_name: $
          draft: false
          prerelease: false
      - name: Upload zip file
        id: upload-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: $
        with:
          upload_url: $
          asset_path: ./$.zip
          asset_name: $-$.zip
          asset_content_type: application/zip
      - name: Upload main.js
        id: upload-main
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: $
        with:
          upload_url: $
          asset_path: $/main.js
          asset_name: main.js
          asset_content_type: text/javascript
      - name: Upload manifest.json
        id: upload-manifest
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: $
        with:
          upload_url: $
          asset_path: $/manifest.json
          asset_name: manifest.json
          asset_content_type: application/json
    # - name: Upload styles.css
    #   id: upload-css
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: $
    #   with:
    #     upload_url: $
    #     asset_path: $/styles.css
    #     asset_name: styles.css
    #     asset_content_type: text/css
